### ISSUE TITLE
Generated config file typo

### ISSUE THREAD

**Issue by ethack** [whatever4711/picapport#1]
The configuration generated by the Dockerfile seems to have a typo in it.
[This line](https://github.com/whatever4711/picapport/blob/master/Dockerfile#L25) has `irobot.root.0.path=/srv/photos` instead of `robot.root.0.path=/srv/photos` (difference is the extra 'i' on the front).  The default config file [here](https://github.com/whatever4711/picapport/blob/master/config/picapport.properties#L2) has it correct.

**Comment by whatever4711** [comment]
Removed with Picapport Version 7.4.00
