### ISSUE TITLE
object heap space error

### ISSUE THREAD

**Issue by YasserAntonio** [whatever4711/picapport#7]
Hello

I'm trying to run on my raspberry 3 ( I tried with my 4 too) this image whatever4711/picapport:linux-arm32v6-8.3.00 but I keep having this error: 

logs : 
```bash
Starting picapport_image_center_1 ... done
Attaching to picapport_image_center_1
image_center_1  | Error occurred during initialization of VM
image_center_1  | Could not reserve enough space for 2097152KB object heap
```

here is my docker-compose file : 

```bash
version: '3'

services:
  image_center:
    image: whatever4711/picapport:linux-arm32v6-8.3.00
    environment:
      - Xms=512m
      - Xmx=1g
      - PICAPPORT_LANG=fr
    volumes:
      - /home/pi/picapport/config:/opt/picapport/.picapport
      - /home/pi/photos:/srv/photos
    ports:
      - 8082:80
```

I tried different variation of the Xms and Xmx variables but I keep having the same issue. 

Any idea on how to solve this ?

**Comment by oldspace** [comment]
I have the exact same issue on my RPi4 with 8GB of RAM. I have raised Xms and Xms up to 2049M but no change.

**Comment by ghost** [comment]
The env variables in the compose file need to be uppercase, `XMX`  and `XMS`, [see the Dockerfile](https://github.com/whatever4711/picapport/blob/757cdb8d87a4fce21eb00bf7565cd817b5750814/Dockerfile#L26).

With the lowercase spelling in the example compose file the container always uses the default values of 256m/2048m.

**Comment by whatever4711** [comment]
I updated the Readme on the docker-compose file. It should be working now and I consider the issue closed.
