### ISSUE TITLE
DB Rescan on every start

### ISSUE THREAD

**Issue by AlexanderSch90** [whatever4711/picapport#9]
Hey, is it right that the DB is scanned on every start of the container? Or is it possible to set an ENV?
My Rescan takes over 3 hours... 
Thanks

**Comment by whatever4711** [comment]
Hi, I adjusted the docker-compose file in the Readme. By adding a volume for the cache, the rescan should not happen anymore. Nevertheless, there are some adjustments one can take by referring to picapport's server documentation [here](https://wiki.picapport.de/display/PIC/PicApport-Server+Guide). Finally, I consider this issue closed.
